### PR TITLE
76586 ft changes for qadeploy stage

### PR DESCRIPTION
**Pull request by surendrabehara2022**
Hi,
Added FT's change for QAdeploy stage.

### CODE REVIEW

**Review by mattwin1 — APPROVED** [review]
LGTM

**Review by DanOwenUKHO — CHANGES_REQUESTED** [review]
Is there an pipeline that has run through to QA for this change?

**Comment by surendrabehara2022** [comment]
> Is there an pipeline that has run through to QA for this change?

Yes, and the pipeline link for reference is https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_build/results?buildId=140427&view=logs&s=35993824-b2e0-5c8d-318b-9998fc9c0f64

**Review by DanOwenUKHO — APPROVED** [review]
LGTM

**Pull request merged**
