### PR TITLE
Dev/149512 investigate existing failing ft

### PR DESCRIPTION
**Pull request by rushikeshkhopatkar**
Hi,

This PR consists of changes to SCS & FSS mock and some of the existing Functional tests to ensure all FT's run using mock.

Please review the same.

### CODE REVIEW

**Review by gaurav15233 — APPROVED** [review]
LGTM

**Review by jagannathsankpal — APPROVED** [review]
LGTM

**Review by RaviK2233 — APPROVED** [review]
Had a Test code walk through from Rushi and looks good.

**Review by richardAhz — APPROVED** [review]
LGTM

**Pull request merged**
