### PR TITLE
Correct documentation around the productData endpoint and sinceDateTime

### PR DESCRIPTION
**Pull request by rockydevnet**

### CODE REVIEW

**Comment by barrie-cooper** [comment]
When making changes to the Open API definition we should also update the comments in ProductDataController.cs that are used to generate the Swagger definition so that the two versions remain in sync.

**Comment by rockydevnet** [comment]
> When making changes to the Open API definition we should also update the comments in ProductDataController.cs that are used to generate the Swagger definition so that the two versions remain in sync.

To be honest, I would much rather remove the Swashbuckle entirely. I don't believe it is adding any value as the Swashbuckle endpoint isn't exposed to anyone, it creates a maintenance headache, and adds confusion as to the source of the truth. What do you guys think?

**Comment by barrie-cooper** [comment]
> > When making changes to the Open API definition we should also update the comments in ProductDataController.cs that are used to generate the Swagger definition so that the two versions remain in sync.
> 
> To be honest, I would much rather remove the Swashbuckle entirely. I don't believe it is adding any value as the Swashbuckle endpoint isn't exposed to anyone, it creates a maintenance headache, and adds confusion as to the source of the truth. What do you guys think?

I personally think the Swagger does add value and is exposed to developers without having to go via APIM.  Also given that this API should really be changing now I don't consider it too much of headache.

So, I have made the corresponding changes to:
- UKHO.ExchangeSetService.API/UKHO.ExchangeSetService.API/Controllers/ProductDataController.cs

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Pull request merged**
