### PR TITLE
11476-added tagging for smoke and qconly tests AB#11476 AB#19038

### PR DESCRIPTION
**Pull request by kajalkundu**
This pull request for tagging test cases whether smoke tests and qc environment only.

### CODE REVIEW

**Review by barrie-cooper — APPROVED** [review]
LGTM

**Review by martyn-fewtrell — APPROVED** [review]
Looks good

**Comment by barrie-cooper** [comment]
@kajalkundu there are 2 failing tests in the `Run Functional tests` task:

https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_build/results?buildId=22328&view=logs&j=76517618-47a2-5f91-2a14-b56ef45870fc&t=75d84b3b-1875-5f3c-9a6b-3e63ad4d2a60

**Review by janvi13603 — COMMENTED** [review]
Looks good to me. I will approve PR once pipeline is green and all acceptances tests are passing.

**Pull request merged**
