### PR TITLE
Testing - Update AIO updatenumber in FT AB#81037

### PR DESCRIPTION
**Pull request by Arit14975**
Hi,

This PR contains a minor change in update Number for AIO cell to facilitate Functional Tests.

Thanks.

### CODE REVIEW

**Review by Mayuresh-Gawde — APPROVED** [review]
LGTM

**Review by DanOwenUKHO — CHANGES_REQUESTED** [review]
Will we expect these tests to fail every time the update number is changed?

**Review by DanOwenUKHO — APPROVED** [review]

**Comment by Mayuresh-Gawde** [comment]
> > > Will we expect these tests to fail every time the update number is changed?
> > 
> > 
> > Yes Dan, whenever the data change for AIO cell happen on QA.
> 
> Can these values be moved to a common area so they only need to be updated once. We need a comment referencing that they need updating as data change in QA happens just so we add some future proofing for code upkeep

Hi Dan, we have moved it to AppSettings.JSON and pushed.

**Review by ray-sj — APPROVED** [review]
thanks for the updates looking good. just a note that hopefully these changes are also made to the other code will need to confirm

**Pull request merged**
