### PR TITLE
Dev/148564 verify status codes for created endpoints

### PR DESCRIPTION
**Pull request by pralesh15295**
Hi,
This PR contains code changes, unit test cases.
Please review the same

Thanks

### CODE REVIEW

**Comment by pralesh15295** [comment]
> WhenInvalidSinceDateTimeInRequest_ThenGetSinceDateTimeReturnsInternalServerError()

Hi Richard, 
Thanks for your review, these unit test are for internal server error when we received any scs response other than 200 So, to avoid confusion we have renamed the unit test's names and for invalid request we have handled other unit tests.

**Review by richardAhz — APPROVED** [review]
LGTM

**Review by jagannathsankpal — APPROVED** [review]
LGTM

**Review by gaurav15233 — APPROVED** [review]
LGTM

**Review by gaurav15233 — APPROVED** [review]
LGTM

**Review by jagannathsankpal — APPROVED** [review]
Changes looks good to me

**Pull request merged**
